package com.example.mutualrisk.common.constants;

public class MailTemplate {

	public static String template = ""
		+ "<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" style=\"border-collapse:collapse\">\n"
		+ "                    \n"
		+ "                    <tbody><tr>\n"
		+ "                        <td width=\"620\" height=\"28\" style=\"font-size:0\"></td>\n"
		+ "                    </tr>\n"
		+ "                    \n"
		+ "                    <tr>\n"
		+ "                        <td width=\"620\" style=\"font-size:0\">\n"
		+ "                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" style=\"border-collapse:collapse\">\n"
		+ "                                <tbody><tr>\n"
		+ "                                    <td width=\"320\" style=\"font-size:0;text-align:right\">\n"
		+ "                                        <span style=\"font-family:'Nanum Gothic','Malgun Gothic','dotum','AppleGothic',Helvetica,Arial,Sans-Serif;font-size:16px;line-height:1.4;letter-spacing:-1.2px\"><strong>뮤추얼리스크 </strong></span>\n"
		+ "                                    </td>\n"
		+ "                                </tr>\n"
		+ "                            </tbody></table>\n"
		+ "                        </td>\n"
		+ "                    </tr>\n"
		+ "                    \n"
		+ "                    <tr>\n"
		+ "                        <td width=\"620\" height=\"28\" style=\"font-size:0\"></td>\n"
		+ "                    </tr>\n"
		+ "                    \n"
		+ "                    \n"
		+ "                    <tr>\n"
		+ "                        <td width=\"620\" style=\"font-size:0\">\n"
		+ "                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" style=\"border-collapse:collapse\">\n"
		+ "                                <tbody><tr>\n"
		+ "                                    <td width=\"40\" style=\"font-size:0;background-color:#fff;border-radius:24px 0 0 24px\"></td>\n"
		+ "                                    <td width=\"540\" style=\"font-size:0;background-color:#fff\">\n"
		+ "                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" style=\"border-collapse:collapse\">\n"
		+ "                                            <tbody><tr>\n"
		+ "                                                <td width=\"540\" height=\"60\" style=\"font-size:0\"></td>\n"
		+ "                                            </tr>\n"
		+ "                                            <tr>\n"
		+ "                                                <td width=\"540\" style=\"font-size:0\">\n"
		+ "                                                    <span style=\"font-family:'Nanum Gothic','Malgun Gothic','dotum','AppleGothic',Helvetica,Arial,Sans-Serif;font-size:32px;line-height:1.4;letter-spacing:-1.2px\">\n"
		+ "                                                        <strong>포트폴리오 자산 변동 안내</strong>\n"
		+ "                                                    </span>\n"
		+ "                                                </td>\n"
		+ "                                            </tr>\n"
		+ "                                            <tr>\n"
		+ "                                                <td width=\"540\" height=\"60\" style=\"font-size:0\"></td>\n"
		+ "                                            </tr>\n"
		+ "                                            <tr>\n"
		+ "                                                <td width=\"540\" style=\"font-size:0\">\n"
		+ "                                                    <span style=\"font-family:'Nanum Gothic','Malgun Gothic','dotum','AppleGothic',Helvetica,Arial,Sans-Serif;font-size:16px;line-height:1.4;color:#000;letter-spacing:-1.2px\">\n"
		+ "                                                        [뮤추얼리스크] 포트폴리오 자산 변동 안내\n"
		+ "                                                    </span>\n"
		+ "                                                </td>\n"
		+ "                                            </tr>\n"
		+ "                                            <tr>\n"
		+ "                                                <td width=\"540\" height=\"20\" style=\"font-size:0\"></td>\n"
		+ "                                            </tr>\n"
		+ "                                            <tr>\n"
		+ "                                                <td width=\"540\" style=\"font-size:0\">\n"
		+ "                                                    <span style=\"font-family:'Nanum Gothic','Malgun Gothic','dotum','AppleGothic',Helvetica,Arial,Sans-Serif;font-size:16px;line-height:1.4;color:#000;letter-spacing:-1.2px\">\n"
		+ "  														{{lowerBoundAssets}}\n"
		+ "  														{{upperBoundAssets}}\n"
		+ "  														{{increasedWeightAssets}}\n"
		+ "  														{{decreasedWeightAssets}}\n"
		+ "                                                    </span>\n"
		+ "                                                </td>\n"
		+ "                                            </tr>"
		+ "                                             <tr><td>\n"
		+ "                                             <tr>\n"
		+ "                                                <td width=\"540\" height=\"40\" style=\"font-size:0\"></td>\n"
		+ "                                            </tr>\n"
		+ "                                            <tr>\n"
		+ "                                                <td width=\"540\" style=\"font-size:0\">\n"
		+ "                                                    <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" style=\"border-collapse:collapse\">\n"
		+ "                                                        <tbody><tr>\n"
		+ "                                                            <td width=\"140\" height=\"54\" style=\"font-size:0\"></td>\n"
		+ "                                                            <td width=\"260\" height=\"54\" align=\"center\" bgcolor=\"#ed2e2e\" style=\"padding:0 17px;background-color:#2196F3;border-radius:48px;text-align:center\">\n"
		+ "                                                                <a href=\"https://j11a607.p.ssafy.io\" title=\"새 창 이동\" style=\"display:block;padding:14px 15px 16px;font-weight:bold;font-size:18px;text-decoration:none;color:#fff;letter-spacing:-1px\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://www.skcareers.com/MyPage/RecruitProcess/R240992&amp;source=gmail&amp;ust=1728541467830000&amp;usg=AOvVaw2GPDYzq1KZKwttBIsQq_BG\">홈페이지로 이동</a>\n"
		+ "                                                            </td>\n"
		+ "                                                            \n"
		+ "                                                            <td width=\"140\" height=\"54\" style=\"font-size:0\"></td>\n"
		+ "                                                        </tr>\n"
		+ "                                                    </tbody></table>\n"
		+ "                                                </td>\n"
		+ "                                            </tr>\n"
		+ "                                            <tr>\n"
		+ "                                                <td width=\"540\" height=\"60\" style=\"font-size:0\"></td>\n"
		+ "                                            </tr>\n"
		+ "                                        </tbody></table>\n"
		+ "                                    </td>\n"
		+ "                                    <td width=\"40\" style=\"font-size:0;background-color:#fff;border-radius:0 24px 24px 0\"></td>\n"
		+ "                                </tr>\n"
		+ "                            </tbody></table>\n"
		+ "                        </td>\n"
		+ "                    </tr>\n"
		+ "                    <tr>\n"
		+ "                        <td width=\"620\" height=\"28\" style=\"font-size:0\"></td>\n"
		+ "                    </tr>\n"
		+ "                    <tr>\n"
		+ "                        <td width=\"620\" height=\"12\" style=\"font-size:0\"></td>\n"
		+ "                    </tr>\n"
		+ "                    <tr>\n"
		+ "                        <td width=\"620\" style=\"font-size:0\">\n"
		+ "                            <span style=\"font-family:'Nanum Gothic','Malgun Gothic','dotum','AppleGothic',Helvetica,Arial,Sans-Serif;font-size:12px;color:#999;line-height:1.4;letter-spacing:-0.5px\"> COPYRIGHT© MutualRisk. ALL RIGHTS RESERVED. </span>\n"
		+ "                        </td>\n"
		+ "                    </tr>\n"
		+ "                    <tr>\n"
		+ "                        <td width=\"620\" height=\"28\" style=\"font-size:0\"></td>\n"
		+ "                    </tr>\n"
		+ "                </tbody></table>";
}
